name: fchat
description: A complete and beautiful chat wrapper for Flutter.
version: 1.0.0

homepage: https://www.example.com

license: MIT

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  phosphor_flutter: ^2.0.0
  flutter_keyboard_visibility: ^5.4.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
